# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='courses',
            new_name='course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='options',
        ),
    ]
